# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: JDC_PUSH

on:
    workflow_dispatch:
    schedule:
        - cron: "0 23 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jdc_push

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: 设置运行环境-Node.js 12
              uses: actions/setup-node@v2
              with:
                  node-version: "15.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行 【京东云推送】"
              run: |
                  node source_of_happiness.js
              env:
                  # 推送专用
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
                  QQ_SKEY: ${{ secrets.QQ_SKEY }}
                  QQ_MODE: ${{ secrets.QQ_MODE }}
                  QYWX_KEY: ${{ secrets.QYWX_KEY }}
                  QYWX_AM: ${{ secrets.QYWX_AM }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
                  # 安全配置
                  CORE_URL: ${{ secrets.CORE_URL }}
                  AES_IV: ${{ secrets.AES_IV }}
                  AES_KEY: ${{ secrets.AES_KEY }}
                  EXTEND_URL: ${{ secrets.EXTEND_URL }}
                  # 通用配置
                  SYNC_URL: ./javascript/jdc_push.js
                  # 独立配置
                  JDC_WSKEY: ${{ secrets.JDC_WSKEY }} # 从京东云无线宝中获取
                  JDC_DEVICENAME: ${{ secrets.JDC_DEVICENAME }} # 设备名 mac后6位:设置的名称，多个使用&连接
                  JDC_RECORDSNUM: ${{ secrets.JDC_RECORDSNUM }} # 查询记录数,纯数字
