# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: JOY_DAILY

on:
    workflow_dispatch:
    schedule:
        - cron: "20 0-23/2 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_joy

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: 设置运行环境-Node.js 12
              uses: actions/setup-node@v2
              with:
                  node-version: "15.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行 【宠汪汪】"
              run: |
                  node source_of_happiness.js
              env:
                  # 推送专用
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
                  QQ_SKEY: ${{ secrets.QQ_SKEY }}
                  QQ_MODE: ${{ secrets.QQ_MODE }}
                  QYWX_KEY: ${{ secrets.QYWX_KEY }}
                  QYWX_AM: ${{ secrets.QYWX_AM }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
                  # 安全配置
                  CORE_URL: ${{ secrets.CORE_URL }}
                  AES_IV: ${{ secrets.AES_IV }}
                  AES_KEY: ${{ secrets.AES_KEY }}
                  EXTEND_URL: ${{ secrets.EXTEND_URL }}
                  # 通用配置
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
                  JD_DEBUG: ${{ secrets.JD_DEBUG }}
                  SYNC_URL: ./data/jd_scripts/jd_joy.js
                  #独立配置
                  JOY_RUN_FLAG: ${{ secrets.JOY_RUN_FLAG }} # 宠汪汪是否赛跑,是否参加赛跑(默认参加双人赛跑),false为否,true为是，脚本默认是true
                  JOY_TEAM_LEVEL: ${{ secrets.JOY_TEAM_LEVEL }} # 宠汪汪参加什么级别的赛跑,参加几人的赛跑,可选数字为2,10,50，其中2代表参加双人PK赛，10代表参加10人突围赛，50代表参加50人挑战赛(注：此项功能在JOY_RUN_FLAG为true的时候才生效)，如若想设置不同账号参加不同类别的比赛则用&区分即可(如下三个账号：2&10&50)
                  # 额外配置
                  SMART_REPLACE: ${{ secrets.SMART_REPLACE }} # 通用替换规则,支持文字替换和正则替换,数据会进行base64解密后使用,[{"match":"要替换的内容",replace:"替换后的内容","desc":"方便自己查看的内容描述","condition":"替换的前提条件,没有就不要填"}]
