name: Note163Checkin

on:
    workflow_dispatch:
    schedule:
        - cron: 0 2 * * *
    watch:
        types: [started]
    repository_dispatch:
        types: note163

# 密码需用MD5加密工具加密，加密格式为32位[小]:(https://tool.chinaz.com/tools/md5.aspx)
# 支持多账号，账号之间与密码之间用半角逗号分隔，账号于密码的个数要对应
# 示例：YOUDAO_USER:123456,24678，YOUDAP_PWD:cxkjntm,jntmcxk

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Python
              run: |
                  sudo apt update && \
                  sudo apt install python3

            - name: requirements
              run: |
                  pip3 install requests

            - name: 【有道云笔记签到】
              run: |
                  user='${{ secrets.YOUDAO_USER }}'
                  pwd='${{ secrets.YOUDAP_PWD }}'


                  user_list=()
                  pwd_list=()
                  IFS=" "
                  for u in ${user[*]}
                  do
                  user_list[${#user_list[*]}]=${u}
                  done
                  for p in ${pwd[*]}
                  do
                  pwd_list[${#pwd_list[*]}]=${p}
                  done
                  user_num=${#user_list[*]}
                  pwd_num=${#pwd_list[*]}
                  if [ $user_num != $pwd_num ];then
                  echo "账号和密码个数不对应"
                  exit 1
                  else
                  echo "共有 $user_num 个账号，即将开始签到"
                  fi
                  for ((i=0;i<$user_num;i++))
                  do
                  python3 python/note163.py <<EOF
                  ${user_list[$i]}
                  ${pwd_list[$i]}
                  EOF
                  done
