name: AA_REPO_SYNC

on:
    workflow_dispatch:
    repository_dispatch:
        types: repo_sync

jobs:
    repo-sync:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: "【基础数据同步】"
              uses: repo-sync/github-sync@v2
              with:
                  source_repo: ${{ secrets.SOURCE_REPO }}
                  source_branch: "main"
                  destination_branch: "main"
                  github_token: ${{ secrets.PAT }}